### ISSUE TITLE
feat: Propose Standard Input Output Sizes 

### ISSUE THREAD

**Issue by thomas-quadratic** [keep-starknet-strange/poseidon-rs#5]
# Feature Request

**Describe the Feature Request**

We observed some discrepancies in the expected input and output sizes depending on the implementation. We would like to propose here a standard regarding those sizes and the corresponding hashing, up for debate. 

**Describe Preferred Solution**

We would like to follow sponge constructions as described in the following articles:
- [keccak-team-article](https://keccak.team/files/CSF-0.1.pdf)
- [poseidon-article](https://eprint.iacr.org/2019/458.pdf)

In particular, the state is made of an outer state with $rate$-elements and an inner state with $capacity$-elements. Hashing is performed as follows:
- Absorb $rate$-elements into the outer state and permute the state.
- Repeat absorption until all the message is absorbed.
- Squeeze elements out the outer state, permuting every $rate$-elements. 

In the process, the inner state should never directly be affected by inputs and should never be outputted.

Note that if the message length is not a multiple of $rate$, the function panics. Issue #6 discusses this further.

**Describe Alternatives**

If we’re not mistaken, this is not completely inline with this [repos](https://github.com/starkware-industries/poseidon).
Here, Poseidon3 for example takes 3 inputs and outputs 3 elements, although the rate is 2 and capacity 1. 
We deduced (maybe wrongly) that the 3rd input was added to the inner state and that the 3rd output was taken from the inner state.
Concretely, we propose in that case to take 2 inputs and to output the first 2 elements

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

The current implementation follows the proposed solution already, but if modifications are needed, yes for a PR

**Comment by liorgold2** [comment]
The repo mentioned above refers only to the permutation function, not the hash function. The hash function will use the sponge construction (which is the process described above).

**Comment by DavidLevitGurevich** [comment]
we will have 3 versions of hash functions based on the permutation mentioned above:
1. hash two elements: return the first element of poseidon3_perm([input1, input2, 2])
2. hash a single element: return the first element of poseidon3_perm([input, 0, 1])
3. sponge construction: given a list of field elements, append a 1 and maybe also a 0 (to complete to an even sized list). start with a state of 3 zeros and then in each iteration add two inputs to the first two elements of the state and apply the permutation. finally return the first element of the state.

**Comment by thomas-quadratic** [comment]
> The repo mentioned above refers only to the permutation function, not the hash function. The hash function will use the sponge construction (which is the process described above).

Thanks for the clarification, indeed it makes sense ! 

> we will have 3 versions of hash functions based on the permutation mentioned above:
> 
> 1. hash two elements: return the first element of poseidon3_perm([input1, input2, 2])
> 2. hash a single element: return the first element of poseidon3_perm([input, 0, 1])
> 3. sponge construction: given a list of field elements, append a 1 and maybe also a 0 (to complete to an even sized list). start with a state of 3 zeros and then in each iteration add two inputs to the first two elements of the state and apply the permutation. finally return the first element of the state.

Thanks, it's clear ! With the current implem, the only problem is that the inner state cannot be initialized with other elements than 0, so we'll have to change that for point 1 and 2.
