### ISSUE TITLE
feat: Hashing Messages of any Length

### ISSUE THREAD

**Issue by thomas-quadratic** [keep-starknet-strange/poseidon-rs#6]
# Feature Request

**Describe the Feature Request**

We propose to accept messages of any length, leading to a deterministic output in all cases. Currently, hash functions panic if the length is not a multiple of $rate$.

**Describe Preferred Solution**

One solution would be to use a sponge-compliant padding rule. In simple terms, sponge-compliance means that for any 2 different messages, their padded counterparts are also different.

There are many possible compliant rules. Perhaps the simplest one is to concatenate 1 to the message, and then to pad with 0s if necessary to make the padded message's length a multiple of $rate$.

Note that if sponge-compliance is necessary, it is unclear to us if it is sufficient for security. A security analysis should be performed for padding rules for Poseidon.

See for example [keccak-team-article](https://keccak.team/files/CSF-0.1.pdf) for further details on padding rules and sponge constructs.

**Describe Alternatives**

Anyone ?

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by LucasLvy** [comment]
Let's leave the padding to the caller so that we keep as much flexibility as we can.

**Comment by thomas-quadratic** [comment]
Sound good to me!
