### ISSUE TITLE
feat: add support for no_std

### ISSUE THREAD

**Issue by thomas-quadratic** [keep-starknet-strange/poseidon-rs#7]
# Feature Request

**Describe the Feature Request**

Add support for no_std. This would allow in particular to target bare-metal environments.

**Additional Context**

Requested by @abdelhamidbakhta 
See https://github.com/lambdaclass/cairo-rs/issues/770 for how this could be done.

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes
- [ ] No

**Comment by EvolveArt** [comment]
@thomas-quadratic I've refractored `no_std` compatibility in my own [fork](https://github.com/EvolveArt/poseidon-rs/tree/feature/no-std-refractor). 
However I want to highlight a major issue to make it usable in other rust projects : 
- The current `cargo.toml` file has 
```toml
crate-type = ["staticlib", "lib"]
``` 
this yields the following errors when trying to compile to `no_std`
```rust
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait

error: `#[panic_handler]` function required, but not found
```

What should be done to solve this is change to
```toml
crate-type = ["rlib", "lib"]
``` 

More info in the [docs](https://doc.rust-lang.org/reference/linkage.html)

If you could give some explanation on your choice to export to `staticlib` would be awesome!
We can either find some low-level way of making this work which I don't absolutely know right now **OR** we could have 2 versions in parallel for different crate types.

**Comment by thomas-quadratic** [comment]
Thanks @EvolveArt  for pointing out the problem, and also the refactoring.

In PR #12 , I removed staticlib from the crate-types and instead included in the doc the way to compile it as a staticlib with C-bindings if needed, for example for the EIP. In fact, initially, the target was the EIP, but it makes sense to make it a core rust lib for a broader audience.

The refactoring is now complete with PR #12, and removes the dependencies even to alloc, which makes sense for a hash function in my opinion, although a bit rough on the edges due to multiple const generics.

Also, I like your way of structuring the project to conditionally allow for std/no_std. We can merge both, I can do it if you wish.
